name: Publish to NPM

on:
  push:
    branches:
      - main # Runs on push to the main branch

jobs:
  publish:
    name: Publish NPM Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version
          registry-url: https://registry.npmjs.org/

      - name: Configure NPM Token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build # Adjust this if your project doesn't require a build step

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
